### PR TITLE
Patch window sensor

### PR DESCRIPTION
**Pull request by DanielWeeber**
Fix for #14

### CODE REVIEW

**Comment by normen** [comment]
Somehow it looks like something was broken with this change (or the one before). I can't seem to control my heating AT ALL anymore. Any ideas? What exactly did you change in the library (I mean in terms of code, I know what you changed functionally).

**Comment by DanielWeeber** [comment]
No problems here. Any output in the log? Also no changes since this PR at all on my repos.

maxcube-commandparser.js 8,209, 221,239

**Comment by normen** [comment]
Hm, do you use the latest 0.9.3 version? Maybe one of my latest fixes did that? Not really possible either though... I'll keep checking my setup, thanks!

**Comment by normen** [comment]
I'm seeing all kinds of funny behavior. Now the thermostats report "0" as target temperature, that never happened before..

**Comment by DanielWeeber** [comment]
Cannot confirm any of that. Just tried it while away from home - even with iOS11 no problem.
Will check the version when I'm at home.

**Comment by normen** [comment]
Wait it looks like I can't even control them from the Max! software..

Hm, guess this is another issue. Theres a problem where when the thermostats report a wireless error I have to log in with the Max! software to confirm the error, before I do that I can't control them from HomeKit anymore. Maybe this is a similar thing. Maybe the maxcube library somehow confuses the cube.

**Pull request merged**
