### PR TITLE
Patch Window Sensor

### PR DESCRIPTION
**Pull request by DanielWeeber**
Make Window Sensors available in HomeKit via homebridge-platform-maxcube and forked version of library.

Battery low of Window Sensor does not work yet (not reported from library), will fix that in the future.

Limit Thermostat Setting to max 30 Degrees, so you cannot enter invalid value in HomeKit (slide to more than 30 degrees)

Change this.name to only contain the name, not the room in brackets.

### CODE REVIEW

**Comment by normen** [comment]
Hey, thanks for this, theres a few issues with the code though.

1) The window sensors should be optional via a config parameter
2) The forked library should be in npm with a proper version etc.
3) The name of the room in brackets is needed when you have many thermostats and rooms. I for example would be presented with a huge list of "West" "West" "East" "East" and wouldn't know which is which. I guess your attempt at cleaning up the names could be solved via the extended manufacturer info of the thermostats but its not really a clean solution either.

Cheers,
Normen

**Comment by DanielWeeber** [comment]
1+2: will fix that. Thanks for the input.
3: You only need to set up your system once. I don't like that it shows as 
"
Living Room
Thermostat Picture (Living Room)
"
I could implement another config switch for that?

**Comment by normen** [comment]
I am aware of the "issue" and what you're trying to "fix". Still it doesn't justify a setup process of an hour or so because you're trying to figure out which thermostat is which.

I guess changing the name during and after startup won't work because its used to identify the device within homebridge? Not sure about that though, no idea how the HAP stack converts devices to ID numbers.

Another option could be implementing some kind of "identify" function. For example changing the temperature to 30 for a short while or something. Problem with that would be that with large setups that could quickly use up the RF quota of the MAX! Cube and you'd end up not being able to control the system anymore for an hour.

**Comment by DanielWeeber** [comment]
1. Done. Readme should be updated for this.
2. Done. Called "maxcube-window".
3. Removed.

Your merge was very fast. I was just testing the changes. 
Commit 5f25c07 had an error. You should revert the changes immediately. Branch updated on my side, is working now.

**Comment by DanielWeeber** [comment]
Battery low is now working.

**Comment by normen** [comment]
Thanks. Can you please start making proper commit messages? Like this its very hard to track when what change happened. As the plugin won't be published via NPM for a while theres no problem with breaking changes or bugs in master.

**Comment by solbadguy2010** [comment]
Sorry if i do not get this. How can i use the Windows Sensors in homebridge now?

**Comment by solbadguy2010** [comment]
Ah, ok. So this is some Beta testing and it will added to the homebridge-platform-maxcube later?

**Comment by DanielWeeber** [comment]
The code is merged and working fine. I don't know when @tobsch will update the npm.

**Comment by solbadguy2010** [comment]
Got it. Thank you for your help!

**Comment by solbadguy2010** [comment]
Hi,
installation was done by using your command. All files also seem to be there:

`pi@Homebridge:/opt/node/lib/node_modules/homebridge-platform-maxcube $ ls
config-sample.json  contactsensor.js  index.js  node_modules  package.json  README.md  thermostat.js
pi@Homebridge:/opt/node/lib/node_modules/homebridge-platform-maxcube $ cd node_modules/
pi@Homebridge:/opt/node/lib/node_modules/homebridge-platform-maxcube/node_modules $ ls
bluebird  maxcube-window  moment
pi@Homebridge:/opt/node/lib/node_modules/homebridge-platform-maxcube/node_modules $ cd maxcube-window/
pi@Homebridge:/opt/node/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube-window $ ls
LICENSE  maxcube-commandfactory.js  maxcube-commandparser.js  maxcube.js  maxcube-lowlevel.js  package.json  README.md`

i then edited the config.json like this:

`  "platforms": [
      {
        "platform": "MaxCubePlatform",
        "name": "MaxCube Platform",
        "ip": "10.0.1.150",
        "port": 62910,
        "windowsensors": true
      }
  ]
}`

sadly, there are no window sensors showing up in the log or the home app.

`[2017-8-18 20:22:37] Loaded plugin: homebridge-platform-maxcube
[2017-8-18 20:22:37] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
[2017-8-18 20:22:37] ---
[2017-8-18 20:22:37] Loaded config.json with 0 accessories and 1 platforms.
[2017-8-18 20:22:37] ---
[2017-8-18 20:22:37] Loading 1 platforms...
[2017-8-18 20:22:37] [MaxCube Platform] Initializing MaxCubePlatform platform...
[2017-8-18 20:22:37] [MaxCube Platform] Try connecting to Max! Cube..
Load homebridge-platform-maxcube.MaxCubePlatform
[2017-8-18 20:22:38] [MaxCube Platform] Connected to Max! Cube..
[2017-8-18 20:22:38] [MaxCube Platform] Initializing platform accessory 'Max! Link'...
[2017-8-18 20:22:38] [MaxCube Platform] Initializing platform accessory 'Thermostat TV (Wohnzimmer)'...
[2017-8-18 20:22:38] [MaxCube Platform] Initializing platform accessory 'Thermostat Esszimmer (Wohnzimmer)'...
[2017-8-18 20:22:38] [MaxCube Platform] Initializing platform accessory 'Thermostat Badezimmer (Badezimmer)'...
[2017-8-18 20:22:38] [MaxCube Platform] Initializing platform accessory 'Thermostat Schlafzimmer (Schlafzimmer)'...
[2017-8-18 20:22:38] [MaxCube Platform] Initializing platform accessory 'Thermostat Sofa (Wohnzimmer)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 000-00-000 │
    └────────────┘

[2017-8-18 20:22:39] Homebridge is running on port 51826.`

Thermostats are running fine. What am i doing wrong?

**Comment by DanielWeeber** [comment]
You have to use "windowsensor" as config-flag, not "windowsensors". Was a typo from me in my previous comment, sorry. I edited my comment.

**Comment by solbadguy2010** [comment]
Works! Thank you again!

**Comment by normen** [comment]
I just noticed that the new HomeBridge version doesn't allow two devices to have the same name while Max! allows having the same name if the devices are in separate rooms. So the names actually HAVE TO be extended with the room name.

Noticed that while including the contact sensor patch for the latest release.

**Pull request merged**
