### PR TITLE
Added automatic device updates, some fixes and cleanups

### PR DESCRIPTION
**Pull request by normen**
A lot of stuff was shuffled around and cleaned up, see the actual changes below. Afaics this concludes what I intend to change about the plugin, I guess after a few days of testing this could be published.

- Fix plugin stalling HomeBridge when cube can't be found on startup
- Added option to use wall thermostat devices via optional allow_wall_thermostat config setting
- Allow using only wall thermostats via only_wall_thermostat
- Added automatic update of data for scene triggers etc.
- Added optional update_interval config option
- Added error status for thermostat devices (visible only in some apps)
- Fix async logic issue with refresh
- Some smaller fixes

### CODE REVIEW

**Comment by normen** [comment]
I tested this during the last days and it seems to work pretty fine. I do still have one other idea about the plugin though, I want to add a switch accessory that allows closing the connection to the Max! Cube.

That way you don't need to stop homebridge to change parameters in the Max! software, you could just flick that switch in the Home app - or even via Siri ;) - and can configure the Max! software. It would also allow the user to try and reconnect a cube if the connection was lost.

I'd still suggest merging this PR first though as people probably look for updated code in this repo and creating and testing the connection switch function will maybe take me a few days.

**Comment by normen** [comment]
Heh, actually it was easier than I thought - closing the Max! Cube connection is now supported as well and the connection is quite robust now, the user can easily reconnect if it should get lost (though it ran for days without issue for me).

**Comment by normen** [comment]
By the way if you're unwilling to maintain the plugin (maybe you moved on to a different system?) I could take over maintenance. You can add me via "npm owner add normen".

**Comment by tobsch** [comment]
Hi Normen,

I was just about to propose this :)
I just added you as contributor on GH and will add you to npmjs too.
Thanks a lot for the work you've done. I am currently using homeassistant together with homebridge, which was a bit more stable. Did you ever take a look at that?

Best,

Tobias

**Comment by normen** [comment]
Hey.

Thanks, I already pushed a new release :) I did it via your repo and kept mine for development, if you want me to move completely to my repo tell me.

Homeassistant looks cool. I like having only one layer between HomeKit and the devices though, as with the Max! Cube theres enough additional web interfaces, apps and whatnot for the devices themselves, then you have to sort them in HomeKit, have automations etc. in all places - I don't want to add another "manager" in there :) 

And HomeBridge itself is really stable, its been running for months here controlling my home. Plus I wanted to brush up my Javascript skills anyway, I am used to more "lowlevel" languages from C/C++ to Obj-C and Java, the whole Node.js ecosystem is kind of cool for checking out JS.

Anyway, thanks for putting out the plugin, it was just the right thing to get started, I hope this will help a few people getting their home automated.

Cheers,
Normen

**Pull request merged**
